### ISSUE TITLE
Is there a Bitcoin script to Miniscript converter available?

### ISSUE THREAD

**Issue by saravanan7mani** [bitcoinerlab/miniscript#7]
Does a function for converting a redeem script or witness script into Miniscript exist?

Reference - [Introduction section from sipa](https://bitcoin.sipa.be/miniscript) `Finally, compatible scripts can easily be converted to Miniscript form - avoiding the need for additional metadata for e.g. signing devices that support it.`

[Code reference](https://github.com/sipa/miniscript/blob/master/bitcoin/script/miniscript.h#L2166C35-L2166C45)

**Comment by landabaso** [comment]
Closed here:
https://twitter.com/landabaso/status/1722577251105931523
